"""empty message

Revision ID: ca744785cf0c
Revises: f5c8e2a79698
Create Date: 2026-03-08 16:55:48.445104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca744785cf0c'
down_revision: Union[str, Sequence[str], None] = 'f5c8e2a79698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
